cc_binary(
    name = "websocket_server_async",
    srcs = ["websocket_server_async.cpp"],
    deps = [
        "//thirtparty/rules_boost:boost",
    ],
)

cc_binary(
    name = "websocket_client_async",
    srcs = ["websocket_client_async.cpp"],
    deps = [
        "//thirtparty/rules_boost:boost",
    ],
)
